2024-09-23 17:49:57,333 - MovieAPI - INFO - Application startup...
2024-09-23 17:53:01,044 - MovieAPI - INFO - Application shutdown...
2024-09-23 17:53:22,217 - MovieAPI - INFO - Application startup...
2024-09-23 17:54:50,709 - MovieAPI - INFO - Application shutdown...
2024-09-23 17:54:51,288 - MovieAPI - INFO - Application startup...
2024-09-23 17:58:14,252 - MovieAPI - INFO - Application shutdown...
2024-09-23 17:58:14,830 - MovieAPI - INFO - Application startup...
2024-09-23 17:59:06,410 - MovieAPI - INFO - Application shutdown...
2024-09-23 18:02:32,676 - FastAPI Movie API - INFO - Application startup...
2024-09-23 18:12:19,208 - FastAPI Movie API - INFO - Application shutdown...
2024-09-23 18:12:20,207 - Movie-API - INFO - Application startup...
2024-09-23 18:12:43,373 - Movie-API - INFO - Application shutdown...
2024-09-23 18:12:44,209 - Movie-API - INFO - Application startup...
2024-09-23 18:15:55,954 - Movie-API - INFO - Application shutdown...
2024-09-23 18:15:56,540 - Movie-API - INFO - Application startup...
2024-09-23 18:16:01,257 - Movie-API - INFO - Application shutdown...
2024-09-23 18:16:01,821 - Movie-API - INFO - Application startup...
2024-09-23 18:19:48,899 - Movie-API - INFO - Application shutdown...
2024-09-25 12:15:32,058 - Movie-API - INFO - Application startup...
2024-09-25 12:16:01,523 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 12:16:01,523 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 12:16:01,523 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 12:16:01,523 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 12:16:01,523 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 12:16:01,523 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 12:16:01,523 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 12:16:01,523 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies
2024-09-25 12:16:01,523 - sqlalchemy.engine.Engine - INFO - [generated in 0.00048s] ()
2024-09-25 12:16:01,523 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 12:16:01,540 - Movie-API - CRITICAL - Unhandled Exception: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation "movies" does not exist
[SQL: SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 514, in _prepare_and_execute
    prepared_stmt, attributes = await adapt_connection._prepare(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 760, in _prepare
    prepared_stmt = await self._connection.prepare(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\asyncpg\connection.py", line 636, in prepare
    return await self._prepare(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\asyncpg\connection.py", line 654, in _prepare
    stmt = await self._get_statement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\asyncpg\connection.py", line 433, in _get_statement
    statement = await self._protocol.prepare(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg\protocol\protocol.pyx", line 166, in prepare
asyncpg.exceptions.UndefinedTableError: relation "movies" does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 572, in execute
    self._adapt_connection.await_(
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 550, in _prepare_and_execute
    self._handle_exception(error)
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 501, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 784, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.ProgrammingError: <class 'asyncpg.exceptions.UndefinedTableError'>: relation "movies" does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\app\api\v1\movies.py", line 46, in get_movies
    return await MovieService.get_all_movies(db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\app\services\movies_services.py", line 20, in get_all_movies
    result = await db.execute(select(Movie))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 461, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 572, in execute
    self._adapt_connection.await_(
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 550, in _prepare_and_execute
    self._handle_exception(error)
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 501, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "C:\Users\cpanda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 784, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation "movies" does not exist
[SQL: SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-09-25 12:22:50,921 - Movie-API - INFO - Application shutdown...
2024-09-25 14:51:14,884 - Movie-API - INFO - Application startup...
2024-09-25 14:51:14,923 - Movie-API - INFO - Application startup...
2024-09-25 14:54:28,107 - Movie-API - INFO - Application startup...
2024-09-25 14:54:28,125 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 14:54:28,125 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 14:54:28,125 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 14:54:28,125 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 14:54:28,125 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 14:54:28,125 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 14:54:28,125 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 14:54:28,138 - sqlalchemy.engine.Engine - INFO - SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = $1::VARCHAR AND pg_catalog.pg_class.relkind = ANY (ARRAY[$2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != $7::VARCHAR
2024-09-25 14:54:28,138 - sqlalchemy.engine.Engine - INFO - [generated in 0.00095s] ('movies', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2024-09-25 14:54:28,138 - sqlalchemy.engine.Engine - INFO - 
CREATE TABLE movies (
	id SERIAL NOT NULL, 
	title VARCHAR, 
	director VARCHAR, 
	release_year INTEGER, 
	PRIMARY KEY (id)
)


2024-09-25 14:54:28,138 - sqlalchemy.engine.Engine - INFO - [no key 0.00063s] ()
2024-09-25 14:54:28,146 - sqlalchemy.engine.Engine - INFO - CREATE INDEX ix_movies_id ON movies (id)
2024-09-25 14:54:28,146 - sqlalchemy.engine.Engine - INFO - [no key 0.00049s] ()
2024-09-25 14:54:28,146 - sqlalchemy.engine.Engine - INFO - CREATE INDEX ix_movies_director ON movies (director)
2024-09-25 14:54:28,146 - sqlalchemy.engine.Engine - INFO - [no key 0.00044s] ()
2024-09-25 14:54:28,156 - sqlalchemy.engine.Engine - INFO - CREATE INDEX ix_movies_title ON movies (title)
2024-09-25 14:54:28,156 - sqlalchemy.engine.Engine - INFO - [no key 0.00039s] ()
2024-09-25 14:54:28,156 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 14:55:09,754 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 14:55:09,754 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 14:56:26,092 - Movie-API - INFO - Application shutdown...
2024-09-25 14:56:26,972 - Movie-API - INFO - Application startup...
2024-09-25 14:56:26,975 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 14:56:26,975 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 14:56:26,993 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 14:56:26,993 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 14:56:26,993 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 14:56:26,993 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 14:56:26,993 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 14:56:26,993 - sqlalchemy.engine.Engine - INFO - SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = $1::VARCHAR AND pg_catalog.pg_class.relkind = ANY (ARRAY[$2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != $7::VARCHAR
2024-09-25 14:56:26,993 - sqlalchemy.engine.Engine - INFO - [generated in 0.00067s] ('movies', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2024-09-25 14:56:26,993 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 14:57:11,037 - Movie-API - INFO - Application shutdown...
2024-09-25 14:57:29,841 - Movie-API - INFO - Application startup...
2024-09-25 14:57:29,868 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 14:57:29,868 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 14:57:29,872 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 14:57:29,872 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 14:57:29,874 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 14:57:29,875 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 14:57:29,877 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 14:57:29,879 - sqlalchemy.engine.Engine - INFO - SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = $1::VARCHAR AND pg_catalog.pg_class.relkind = ANY (ARRAY[$2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != $7::VARCHAR
2024-09-25 14:57:29,880 - sqlalchemy.engine.Engine - INFO - [generated in 0.00054s] ('movies', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2024-09-25 14:57:29,882 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 14:59:00,593 - Movie-API - INFO - Application startup...
2024-09-25 14:59:00,611 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 14:59:00,611 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 14:59:00,611 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 14:59:00,611 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 14:59:00,611 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 14:59:00,611 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 14:59:00,611 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 14:59:00,611 - sqlalchemy.engine.Engine - INFO - SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = $1::VARCHAR AND pg_catalog.pg_class.relkind = ANY (ARRAY[$2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != $7::VARCHAR
2024-09-25 14:59:00,611 - sqlalchemy.engine.Engine - INFO - [generated in 0.00064s] ('movies', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2024-09-25 14:59:00,627 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 15:07:57,588 - Movie-API - INFO - Application shutdown...
2024-09-25 15:07:58,539 - Movie-API - INFO - Application startup...
2024-09-25 15:07:58,571 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 15:07:58,571 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 15:07:58,573 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 15:07:58,574 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 15:07:58,576 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 15:07:58,576 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 15:07:58,578 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 15:07:58,581 - sqlalchemy.engine.Engine - INFO - SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = $1::VARCHAR AND pg_catalog.pg_class.relkind = ANY (ARRAY[$2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != $7::VARCHAR
2024-09-25 15:07:58,582 - sqlalchemy.engine.Engine - INFO - [generated in 0.00061s] ('movies', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2024-09-25 15:07:58,584 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 15:08:11,368 - Movie-API - INFO - Application shutdown...
2024-09-25 15:08:12,339 - Movie-API - INFO - Application startup...
2024-09-25 15:08:12,375 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 15:08:12,375 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 15:08:12,375 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 15:08:12,375 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 15:08:12,375 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 15:08:12,375 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 15:08:12,375 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 15:08:12,375 - sqlalchemy.engine.Engine - INFO - SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = $1::VARCHAR AND pg_catalog.pg_class.relkind = ANY (ARRAY[$2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != $7::VARCHAR
2024-09-25 15:08:12,390 - sqlalchemy.engine.Engine - INFO - [generated in 0.00071s] ('movies', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2024-09-25 15:08:12,393 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 15:08:52,705 - Movie-API - INFO - Application shutdown...
2024-09-25 15:08:53,678 - Movie-API - INFO - Application startup...
2024-09-25 15:08:53,688 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 15:08:53,688 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 15:08:53,688 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 15:08:53,704 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 15:08:53,705 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 15:08:53,705 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 15:08:53,705 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 15:08:53,705 - sqlalchemy.engine.Engine - INFO - SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = $1::VARCHAR AND pg_catalog.pg_class.relkind = ANY (ARRAY[$2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != $7::VARCHAR
2024-09-25 15:08:53,705 - sqlalchemy.engine.Engine - INFO - [generated in 0.00067s] ('movies', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2024-09-25 15:08:53,705 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 15:08:54,585 - Movie-API - INFO - Application shutdown...
2024-09-25 15:08:55,616 - Movie-API - INFO - Application startup...
2024-09-25 15:08:55,636 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 15:08:55,636 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 15:08:55,639 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 15:08:55,640 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 15:08:55,642 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 15:08:55,643 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 15:08:55,646 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 15:08:55,647 - sqlalchemy.engine.Engine - INFO - SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = $1::VARCHAR AND pg_catalog.pg_class.relkind = ANY (ARRAY[$2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != $7::VARCHAR
2024-09-25 15:08:55,647 - sqlalchemy.engine.Engine - INFO - [generated in 0.00048s] ('movies', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2024-09-25 15:08:55,652 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 15:09:05,929 - Movie-API - INFO - Application shutdown...
2024-09-25 15:09:06,945 - Movie-API - INFO - Application startup...
2024-09-25 15:09:06,961 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 15:09:06,965 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 15:09:06,967 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 15:09:06,967 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 15:09:06,970 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 15:09:06,970 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 15:09:06,970 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 15:09:06,970 - sqlalchemy.engine.Engine - INFO - SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = $1::VARCHAR AND pg_catalog.pg_class.relkind = ANY (ARRAY[$2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != $7::VARCHAR
2024-09-25 15:09:06,975 - sqlalchemy.engine.Engine - INFO - [generated in 0.00065s] ('movies', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2024-09-25 15:09:06,978 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 15:10:03,176 - Movie-API - INFO - Application shutdown...
2024-09-25 15:10:05,308 - Movie-API - INFO - Application startup...
2024-09-25 15:10:05,346 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 15:10:05,346 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 15:10:05,348 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 15:10:05,349 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 15:10:05,350 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 15:10:05,351 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 15:10:05,353 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 15:10:05,355 - sqlalchemy.engine.Engine - INFO - SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = $1::VARCHAR AND pg_catalog.pg_class.relkind = ANY (ARRAY[$2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != $7::VARCHAR
2024-09-25 15:10:05,356 - sqlalchemy.engine.Engine - INFO - [generated in 0.00046s] ('movies', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2024-09-25 15:10:05,359 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 15:36:11,039 - Movie-API - INFO - Application shutdown...
2024-09-25 16:12:31,687 - Movie-API - INFO - Application startup...
2024-09-25 16:12:31,705 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 16:12:31,705 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:12:31,705 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 16:12:31,705 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:12:31,715 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 16:12:31,715 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:12:31,717 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:12:31,717 - sqlalchemy.engine.Engine - INFO - SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = $1::VARCHAR AND pg_catalog.pg_class.relkind = ANY (ARRAY[$2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != $7::VARCHAR
2024-09-25 16:12:31,717 - sqlalchemy.engine.Engine - INFO - [generated in 0.00052s] ('movies', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2024-09-25 16:12:31,725 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 16:14:51,368 - Movie-API - INFO - Application shutdown...
2024-09-25 16:16:42,323 - Movie-API - INFO - Application startup...
2024-09-25 16:17:19,502 - Movie-API - INFO - Application shutdown...
2024-09-25 16:25:37,640 - Movie-API - INFO - Application startup...
2024-09-25 16:25:37,665 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 16:25:37,665 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:25:37,665 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 16:25:37,665 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:25:37,665 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 16:25:37,665 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:25:37,665 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:25:37,681 - sqlalchemy.engine.Engine - INFO - SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = $1::VARCHAR AND pg_catalog.pg_class.relkind = ANY (ARRAY[$2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != $7::VARCHAR
2024-09-25 16:25:37,681 - sqlalchemy.engine.Engine - INFO - [generated in 0.00061s] ('movies', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2024-09-25 16:25:37,681 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 16:26:02,056 - Movie-API - INFO - Application shutdown...
2024-09-25 16:26:03,025 - Movie-API - INFO - Application startup...
2024-09-25 16:26:03,041 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 16:26:03,041 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:26:03,041 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 16:26:03,041 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:26:03,057 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 16:26:03,057 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:26:03,057 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:26:03,057 - sqlalchemy.engine.Engine - INFO - SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = $1::VARCHAR AND pg_catalog.pg_class.relkind = ANY (ARRAY[$2::VARCHAR, $3::VARCHAR, $4::VARCHAR, $5::VARCHAR, $6::VARCHAR]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != $7::VARCHAR
2024-09-25 16:26:03,057 - sqlalchemy.engine.Engine - INFO - [generated in 0.00066s] ('movies', 'r', 'p', 'f', 'v', 'm', 'pg_catalog')
2024-09-25 16:26:03,057 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 16:30:13,924 - Movie-API - INFO - Application shutdown...
2024-09-25 16:30:14,747 - Movie-API - INFO - Application startup...
2024-09-25 14:55:09,754 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 16:34:26,240 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:34:26,287 - Movie-API - CRITICAL - Unhandled Exception: Class 'app.models.movie.CreateMovie' is not mapped
Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3473, in add
    state = attributes.instance_state(instance)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\pydantic\main.py", line 856, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'CreateMovie' object has no attribute '_sa_instance_state'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\app\api\v1\movies.py", line 31, in create_movie
    response = await MovieService.create_movie(movie, db)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\app\services\movies_services.py", line 12, in create_movie
    db.add(movie)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 1152, in add
    return self._proxied.add(instance, _warn=_warn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3475, in add
    raise exc.UnmappedInstanceError(instance) from err
sqlalchemy.orm.exc.UnmappedInstanceError: Class 'app.models.movie.CreateMovie' is not mapped
2024-09-25 16:34:26,303 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 16:34:26,303 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:34:26,303 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:34:26,303 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies
2024-09-25 16:34:26,303 - sqlalchemy.engine.Engine - INFO - [generated in 0.00107s] ()
2024-09-25 16:34:26,319 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 16:34:26,319 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:34:26,319 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies
2024-09-25 16:34:26,319 - sqlalchemy.engine.Engine - INFO - [cached since 0.01105s ago] ()
2024-09-25 16:34:26,319 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:34:26,319 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies
2024-09-25 16:34:26,319 - sqlalchemy.engine.Engine - INFO - [cached since 0.0121s ago] ()
2024-09-25 16:34:26,319 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:34:26,319 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies
2024-09-25 16:34:26,319 - sqlalchemy.engine.Engine - INFO - [cached since 0.01327s ago] ()
2024-09-25 16:34:26,319 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:34:26,319 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies
2024-09-25 16:34:26,319 - sqlalchemy.engine.Engine - INFO - [cached since 0.01462s ago] ()
2024-09-25 16:34:26,319 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 16:34:26,319 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 16:34:26,319 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 16:34:26,334 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 16:34:27,181 - Movie-API - INFO - Application startup...
2024-09-25 16:34:52,469 - Movie-API - INFO - Application startup...
2024-09-25 16:35:22,602 - Movie-API - INFO - Application startup...
2024-09-25 16:35:49,013 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 16:35:49,013 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:35:49,013 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 16:35:49,013 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:35:49,013 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 16:35:49,013 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:35:49,013 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:35:49,013 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies
2024-09-25 16:35:49,013 - sqlalchemy.engine.Engine - INFO - [generated in 0.00051s] ()
2024-09-25 16:35:49,030 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 16:36:12,325 - Movie-API - CRITICAL - Unhandled Exception: Class 'app.models.movie.CreateMovie' is not mapped
Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3473, in add
    state = attributes.instance_state(instance)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\pydantic\main.py", line 856, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'CreateMovie' object has no attribute '_sa_instance_state'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\app\api\v1\movies.py", line 31, in create_movie
    response = await MovieService.create_movie(movie, db)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\app\services\movies_services.py", line 12, in create_movie
    db.add(movie)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 1152, in add
    return self._proxied.add(instance, _warn=_warn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3475, in add
    raise exc.UnmappedInstanceError(instance) from err
sqlalchemy.orm.exc.UnmappedInstanceError: Class 'app.models.movie.CreateMovie' is not mapped
2024-09-25 16:36:57,857 - Movie-API - INFO - Application shutdown...
2024-09-25 16:36:59,325 - Movie-API - INFO - Application startup...
2024-09-25 16:37:04,587 - Movie-API - INFO - Application shutdown...
2024-09-25 16:37:05,858 - Movie-API - INFO - Application startup...
2024-09-25 16:37:15,937 - Movie-API - CRITICAL - Unhandled Exception: Class 'app.models.movie.CreateMovie' is not mapped
Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3473, in add
    state = attributes.instance_state(instance)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\pydantic\main.py", line 856, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'CreateMovie' object has no attribute '_sa_instance_state'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\app\api\v1\movies.py", line 31, in create_movie
    response = await MovieService.create_movie(movie, db)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\app\services\movies_services.py", line 12, in create_movie
    db.add(movie)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 1152, in add
    return self._proxied.add(instance, _warn=_warn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3475, in add
    raise exc.UnmappedInstanceError(instance) from err
sqlalchemy.orm.exc.UnmappedInstanceError: Class 'app.models.movie.CreateMovie' is not mapped
2024-09-25 16:38:41,540 - Movie-API - INFO - Application shutdown...
2024-09-25 16:38:42,404 - Movie-API - INFO - Application startup...
2024-09-25 16:39:00,072 - Movie-API - INFO - Application shutdown...
2024-09-25 16:39:01,061 - Movie-API - INFO - Application startup...
2024-09-25 16:39:53,708 - Movie-API - INFO - Application shutdown...
2024-09-25 16:39:54,550 - Movie-API - INFO - Application startup...
2024-09-25 16:40:08,169 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 16:40:08,169 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:40:08,169 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 16:40:08,169 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:40:08,169 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 16:40:08,169 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:40:08,185 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:40:08,185 - sqlalchemy.engine.Engine - INFO - INSERT INTO movies (id, title, director, release_year) VALUES ($1::INTEGER, $2::VARCHAR, $3::VARCHAR, $4::INTEGER)
2024-09-25 16:40:08,185 - sqlalchemy.engine.Engine - INFO - [generated in 0.00058s] (1, 'test', 'test', 1990)
2024-09-25 16:40:08,185 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 16:40:08,202 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:40:08,202 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 16:40:08,202 - sqlalchemy.engine.Engine - INFO - [generated in 0.00067s] (1,)
2024-09-25 16:40:08,202 - Movie-API - INFO - Movie 'test' created successfully.
2024-09-25 16:40:08,202 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 16:40:57,202 - Movie-API - INFO - Application shutdown...
2024-09-25 16:40:58,083 - Movie-API - INFO - Application startup...
2024-09-25 16:41:13,494 - Movie-API - INFO - Application shutdown...
2024-09-25 16:41:14,376 - Movie-API - INFO - Application startup...
2024-09-25 16:41:17,133 - Movie-API - INFO - Application shutdown...
2024-09-25 16:41:18,109 - Movie-API - INFO - Application startup...
2024-09-25 16:42:04,940 - Movie-API - INFO - Application shutdown...
2024-09-25 16:42:05,866 - Movie-API - INFO - Application startup...
2024-09-25 16:42:11,242 - Movie-API - INFO - Application shutdown...
2024-09-25 16:42:12,164 - Movie-API - INFO - Application startup...
2024-09-25 16:43:00,685 - Movie-API - INFO - Application shutdown...
2024-09-25 16:43:01,601 - Movie-API - INFO - Application startup...
2024-09-25 16:43:07,799 - Movie-API - INFO - Application shutdown...
2024-09-25 16:43:08,803 - Movie-API - INFO - Application startup...
2024-09-25 16:43:33,638 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 16:43:33,638 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:43:33,638 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 16:43:33,638 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:43:33,638 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 16:43:33,638 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:43:33,654 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:43:33,654 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 16:43:33,654 - sqlalchemy.engine.Engine - INFO - [generated in 0.00037s] (1,)
2024-09-25 16:43:33,654 - sqlalchemy.engine.Engine - INFO - UPDATE movies SET title=$1::VARCHAR WHERE movies.id = $2::INTEGER
2024-09-25 16:43:33,654 - sqlalchemy.engine.Engine - INFO - [generated in 0.00037s] ('testa', 1)
2024-09-25 16:43:33,654 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 16:43:33,671 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:43:33,671 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 16:43:33,671 - sqlalchemy.engine.Engine - INFO - [generated in 0.00054s] (1,)
2024-09-25 16:43:33,671 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 16:43:33,678 - Movie-API - CRITICAL - Unhandled Exception: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None}
Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None}

2024-09-25 16:58:10,973 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:58:10,973 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 16:58:10,973 - sqlalchemy.engine.Engine - INFO - [cached since 877.3s ago] (1,)
2024-09-25 16:58:10,975 - sqlalchemy.engine.Engine - INFO - UPDATE movies SET title=$1::VARCHAR, director=$2::VARCHAR, release_year=$3::INTEGER WHERE movies.id = $4::INTEGER
2024-09-25 16:58:10,975 - sqlalchemy.engine.Engine - INFO - [generated in 0.00057s] ('new', 'new', 1896, 1)
2024-09-25 16:58:10,975 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 16:58:10,990 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:58:10,994 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 16:58:10,994 - sqlalchemy.engine.Engine - INFO - [cached since 877.3s ago] (1,)
2024-09-25 16:58:10,996 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 16:58:10,996 - Movie-API - CRITICAL - Unhandled Exception: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None}
Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None}

2024-09-25 16:58:12,755 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:58:12,755 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 16:58:12,755 - sqlalchemy.engine.Engine - INFO - [cached since 879.1s ago] (1,)
2024-09-25 16:58:12,755 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 16:58:12,766 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:58:12,766 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 16:58:12,767 - sqlalchemy.engine.Engine - INFO - [cached since 879.1s ago] (1,)
2024-09-25 16:58:12,769 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 16:58:12,769 - Movie-API - CRITICAL - Unhandled Exception: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None}
Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None}

2024-09-25 16:58:36,611 - Movie-API - INFO - Application shutdown...
2024-09-25 16:58:37,420 - Movie-API - INFO - Application startup...
2024-09-25 16:58:42,547 - Movie-API - INFO - Application shutdown...
2024-09-25 16:58:43,429 - Movie-API - INFO - Application startup...
2024-09-25 16:58:46,657 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 16:58:46,657 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:58:46,657 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 16:58:46,657 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:58:46,657 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 16:58:46,657 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 16:58:46,657 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:58:46,665 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 16:58:46,665 - sqlalchemy.engine.Engine - INFO - [generated in 0.00031s] (1,)
2024-09-25 16:58:46,669 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 16:58:46,670 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:58:46,670 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 16:58:46,670 - sqlalchemy.engine.Engine - INFO - [generated in 0.00029s] (1,)
2024-09-25 16:58:46,670 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 16:59:34,794 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:59:34,794 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 16:59:34,794 - sqlalchemy.engine.Engine - INFO - [cached since 48.13s ago] (1,)
2024-09-25 16:59:34,794 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 16:59:36,470 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:59:36,476 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 16:59:36,476 - sqlalchemy.engine.Engine - INFO - [cached since 49.81s ago] (1,)
2024-09-25 16:59:36,477 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 16:59:45,018 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:59:45,018 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies
2024-09-25 16:59:45,022 - sqlalchemy.engine.Engine - INFO - [generated in 0.00054s] ()
2024-09-25 16:59:45,022 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 16:59:56,995 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:59:56,995 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 16:59:56,995 - sqlalchemy.engine.Engine - INFO - [cached since 70.33s ago] (1,)
2024-09-25 16:59:56,995 - sqlalchemy.engine.Engine - INFO - DELETE FROM movies WHERE movies.id = $1::INTEGER
2024-09-25 16:59:56,995 - sqlalchemy.engine.Engine - INFO - [generated in 0.00057s] (1,)
2024-09-25 16:59:56,995 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 16:59:57,013 - Movie-API - CRITICAL - Unhandled Exception: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None}
Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None}

2024-09-25 16:59:58,957 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 16:59:58,959 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 16:59:58,959 - sqlalchemy.engine.Engine - INFO - [cached since 72.29s ago] (1,)
2024-09-25 16:59:58,959 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:00:49,137 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:00:49,137 - sqlalchemy.engine.Engine - INFO - INSERT INTO movies (id, title, director, release_year) VALUES ($1::INTEGER, $2::VARCHAR, $3::VARCHAR, $4::INTEGER)
2024-09-25 17:00:49,137 - sqlalchemy.engine.Engine - INFO - [generated in 0.00043s] (1, 'new', 'ewe', 1909)
2024-09-25 17:00:49,145 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:00:49,145 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:00:49,145 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:00:49,145 - sqlalchemy.engine.Engine - INFO - [cached since 122.5s ago] (1,)
2024-09-25 17:00:49,145 - Movie-API - INFO - Movie 'new' created successfully.
2024-09-25 17:00:49,145 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:00:50,044 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:00:50,044 - sqlalchemy.engine.Engine - INFO - INSERT INTO movies (id, title, director, release_year) VALUES ($1::INTEGER, $2::VARCHAR, $3::VARCHAR, $4::INTEGER)
2024-09-25 17:00:50,044 - sqlalchemy.engine.Engine - INFO - [cached since 0.9036s ago] (1, 'new', 'ewe', 1909)
2024-09-25 17:00:50,044 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:00:50,049 - Movie-API - CRITICAL - Unhandled Exception: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "movies_pkey"
DETAIL:  Key (id)=(1) already exists.
[SQL: INSERT INTO movies (id, title, director, release_year) VALUES ($1::INTEGER, $2::VARCHAR, $3::VARCHAR, $4::INTEGER)]
[parameters: (1, 'new', 'ewe', 1909)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 538, in _prepare_and_execute
    self._rows = deque(await prepared_stmt.fetch(*parameters))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\asyncpg\prepared_stmt.py", line 176, in fetch
    data = await self.__bind_execute(args, 0, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\asyncpg\prepared_stmt.py", line 241, in __bind_execute
    data, status, _ = await self.__do_execute(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\asyncpg\prepared_stmt.py", line 230, in __do_execute
    return await executor(protocol)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg\protocol\protocol.pyx", line 207, in bind_execute
asyncpg.exceptions.UniqueViolationError: duplicate key value violates unique constraint "movies_pkey"
DETAIL:  Key (id)=(1) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 572, in execute
    self._adapt_connection.await_(
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 550, in _prepare_and_execute
    self._handle_exception(error)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 501, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 784, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.IntegrityError: <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "movies_pkey"
DETAIL:  Key (id)=(1) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\app\api\v1\movies.py", line 30, in create_movie
    response = await MovieService.create_movie(movie, db)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\app\services\movies_services.py", line 13, in create_movie
    await db.commit()  # Commit the transaction
    ^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 1009, in commit
    await greenlet_spawn(self.sync_session.commit)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4352, in flush
    self._flush(objects)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4487, in _flush
    with util.safe_reraise():
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4448, in _flush
    flush_context.execute()
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1048, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 572, in execute
    self._adapt_connection.await_(
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 550, in _prepare_and_execute
    self._handle_exception(error)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 501, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 784, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.IntegrityError: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "movies_pkey"
DETAIL:  Key (id)=(1) already exists.
[SQL: INSERT INTO movies (id, title, director, release_year) VALUES ($1::INTEGER, $2::VARCHAR, $3::VARCHAR, $4::INTEGER)]
[parameters: (1, 'new', 'ewe', 1909)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-09-25 17:01:09,929 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:01:09,929 - sqlalchemy.engine.Engine - INFO - INSERT INTO movies (id, title, director, release_year) VALUES ($1::INTEGER, $2::VARCHAR, $3::VARCHAR, $4::INTEGER)
2024-09-25 17:01:09,929 - sqlalchemy.engine.Engine - INFO - [cached since 20.79s ago] (2, 'new', 'ewe', 1909)
2024-09-25 17:01:09,929 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:01:09,929 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:01:09,929 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:01:09,929 - sqlalchemy.engine.Engine - INFO - [cached since 143.3s ago] (2,)
2024-09-25 17:01:09,929 - Movie-API - INFO - Movie 'new' created successfully.
2024-09-25 17:01:09,929 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:01:35,077 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:01:35,078 - sqlalchemy.engine.Engine - INFO - INSERT INTO movies (id, title, director, release_year) VALUES ($1::INTEGER, $2::VARCHAR, $3::VARCHAR, $4::INTEGER)
2024-09-25 17:01:35,078 - sqlalchemy.engine.Engine - INFO - [cached since 45.94s ago] (3, 'new', 'ewe', 1909)
2024-09-25 17:01:35,078 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:01:35,078 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:01:35,078 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:01:35,078 - sqlalchemy.engine.Engine - INFO - [cached since 168.4s ago] (3,)
2024-09-25 17:01:35,089 - Movie-API - INFO - Movie 'new' created successfully.
2024-09-25 17:01:35,090 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:01:43,083 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:01:43,083 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies
2024-09-25 17:01:43,083 - sqlalchemy.engine.Engine - INFO - [cached since 118.1s ago] ()
2024-09-25 17:01:43,083 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:02:23,582 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:02:23,582 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:02:23,582 - sqlalchemy.engine.Engine - INFO - [cached since 216.9s ago] (1,)
2024-09-25 17:02:23,585 - sqlalchemy.engine.Engine - INFO - DELETE FROM movies WHERE movies.id = $1::INTEGER
2024-09-25 17:02:23,585 - sqlalchemy.engine.Engine - INFO - [cached since 146.6s ago] (1,)
2024-09-25 17:02:23,585 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:02:23,596 - Movie-API - CRITICAL - Unhandled Exception: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None}
Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None}

2024-09-25 17:02:38,218 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:02:38,218 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:02:38,218 - sqlalchemy.engine.Engine - INFO - [cached since 231.6s ago] (2,)
2024-09-25 17:02:38,218 - sqlalchemy.engine.Engine - INFO - DELETE FROM movies WHERE movies.id = $1::INTEGER
2024-09-25 17:02:38,218 - sqlalchemy.engine.Engine - INFO - [cached since 161.2s ago] (2,)
2024-09-25 17:02:38,218 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:02:38,234 - Movie-API - CRITICAL - Unhandled Exception: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None}
Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'model_attributes_type', 'loc': ('response',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': None}

2024-09-25 17:12:55,271 - Movie-API - INFO - Application shutdown...
2024-09-25 17:12:56,448 - Movie-API - INFO - Application startup...
2024-09-25 17:13:19,770 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 17:13:19,770 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 17:13:19,770 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 17:13:19,770 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 17:13:19,770 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 17:13:19,787 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 17:13:19,789 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:13:19,791 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies
2024-09-25 17:13:19,791 - sqlalchemy.engine.Engine - INFO - [generated in 0.00052s] ()
2024-09-25 17:13:19,795 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:13:39,669 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:13:39,669 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:13:39,669 - sqlalchemy.engine.Engine - INFO - [generated in 0.00054s] (3,)
2024-09-25 17:13:39,669 - sqlalchemy.engine.Engine - INFO - DELETE FROM movies WHERE movies.id = $1::INTEGER
2024-09-25 17:13:39,669 - sqlalchemy.engine.Engine - INFO - [generated in 0.00048s] (3,)
2024-09-25 17:13:39,669 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:13:39,685 - Movie-API - CRITICAL - Unhandled Exception: 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'id'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'director'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'release_year'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'id'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'director'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'release_year'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}

2024-09-25 17:14:51,533 - Movie-API - INFO - Application shutdown...
2024-09-25 17:14:52,314 - Movie-API - INFO - Application startup...
2024-09-25 17:15:07,015 - Movie-API - INFO - Application shutdown...
2024-09-25 17:15:07,932 - Movie-API - INFO - Application startup...
2024-09-25 17:15:27,644 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 17:15:27,644 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 17:15:27,644 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 17:15:27,644 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 17:15:27,644 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 17:15:27,644 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 17:15:27,658 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:15:27,660 - sqlalchemy.engine.Engine - INFO - INSERT INTO movies (id, title, director, release_year) VALUES ($1::INTEGER, $2::VARCHAR, $3::VARCHAR, $4::INTEGER)
2024-09-25 17:15:27,660 - sqlalchemy.engine.Engine - INFO - [generated in 0.00054s] (1, 'fsfs', 'fsdfs', 1989)
2024-09-25 17:15:27,660 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:15:27,677 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:15:27,678 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:15:27,678 - sqlalchemy.engine.Engine - INFO - [generated in 0.00063s] (1,)
2024-09-25 17:15:27,678 - Movie-API - INFO - Movie 'fsfs' created successfully.
2024-09-25 17:15:27,678 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:15:47,316 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:15:47,316 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:15:47,316 - sqlalchemy.engine.Engine - INFO - [generated in 0.00049s] (1,)
2024-09-25 17:15:47,316 - sqlalchemy.engine.Engine - INFO - DELETE FROM movies WHERE movies.id = $1::INTEGER
2024-09-25 17:15:47,324 - sqlalchemy.engine.Engine - INFO - [generated in 0.00060s] (1,)
2024-09-25 17:15:47,324 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:15:47,334 - Movie-API - CRITICAL - Unhandled Exception: 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'id'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'director'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'release_year'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'id'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'director'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'release_year'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}

2024-09-25 17:16:16,435 - Movie-API - INFO - Application shutdown...
2024-09-25 17:16:31,389 - Movie-API - INFO - Application startup...
2024-09-25 17:21:32,444 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 17:21:32,444 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 17:21:32,444 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 17:21:32,444 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 17:21:32,444 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 17:21:32,444 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 17:21:32,444 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:21:32,454 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:21:32,454 - sqlalchemy.engine.Engine - INFO - [generated in 0.00052s] (1,)
2024-09-25 17:21:32,454 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:21:43,030 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:21:43,030 - sqlalchemy.engine.Engine - INFO - INSERT INTO movies (id, title, director, release_year) VALUES ($1::INTEGER, $2::VARCHAR, $3::VARCHAR, $4::INTEGER)
2024-09-25 17:21:43,030 - sqlalchemy.engine.Engine - INFO - [generated in 0.00064s] (1, 'fsfs', 'fsdfs', 1989)
2024-09-25 17:21:43,030 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:21:43,030 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:21:43,045 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:21:43,045 - sqlalchemy.engine.Engine - INFO - [generated in 0.00067s] (1,)
2024-09-25 17:21:43,045 - Movie-API - INFO - Movie 'fsfs' created successfully.
2024-09-25 17:21:43,045 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:21:55,820 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:21:55,820 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:21:55,820 - sqlalchemy.engine.Engine - INFO - [cached since 23.37s ago] (1,)
2024-09-25 17:21:55,820 - sqlalchemy.engine.Engine - INFO - DELETE FROM movies WHERE movies.id = $1::INTEGER
2024-09-25 17:21:55,820 - sqlalchemy.engine.Engine - INFO - [generated in 0.00052s] (1,)
2024-09-25 17:21:55,820 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:21:55,839 - Movie-API - CRITICAL - Unhandled Exception: 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'id'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'director'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'release_year'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'id'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'director'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'release_year'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}

2024-09-25 17:23:31,566 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:23:31,566 - sqlalchemy.engine.Engine - INFO - INSERT INTO movies (id, title, director, release_year) VALUES ($1::INTEGER, $2::VARCHAR, $3::VARCHAR, $4::INTEGER)
2024-09-25 17:23:31,566 - sqlalchemy.engine.Engine - INFO - [cached since 108.5s ago] (1, 'fsfs', 'fsdfs', 1989)
2024-09-25 17:23:31,566 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:23:31,582 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:23:31,582 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:23:31,582 - sqlalchemy.engine.Engine - INFO - [cached since 108.5s ago] (1,)
2024-09-25 17:23:31,582 - Movie-API - INFO - Movie 'fsfs' created successfully.
2024-09-25 17:23:31,582 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:23:35,840 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:23:35,840 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:23:35,840 - sqlalchemy.engine.Engine - INFO - [cached since 123.4s ago] (1,)
2024-09-25 17:23:35,840 - sqlalchemy.engine.Engine - INFO - DELETE FROM movies WHERE movies.id = $1::INTEGER
2024-09-25 17:23:35,844 - sqlalchemy.engine.Engine - INFO - [cached since 100s ago] (1,)
2024-09-25 17:23:35,845 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:23:35,855 - Movie-API - CRITICAL - Unhandled Exception: 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'id'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'director'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'release_year'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'id'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'director'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'release_year'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}

2024-09-25 17:24:04,754 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:24:04,754 - sqlalchemy.engine.Engine - INFO - INSERT INTO movies (id, title, director, release_year) VALUES ($1::INTEGER, $2::VARCHAR, $3::VARCHAR, $4::INTEGER)
2024-09-25 17:24:04,754 - sqlalchemy.engine.Engine - INFO - [cached since 141.7s ago] (1, 'ada', 'dasa', 1898)
2024-09-25 17:24:04,754 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:24:04,765 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:24:04,765 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:24:04,769 - sqlalchemy.engine.Engine - INFO - [cached since 141.7s ago] (1,)
2024-09-25 17:24:04,770 - Movie-API - INFO - Movie 'ada' created successfully.
2024-09-25 17:24:04,770 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:24:13,808 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:24:13,808 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:24:13,808 - sqlalchemy.engine.Engine - INFO - [cached since 161.4s ago] (1,)
2024-09-25 17:24:13,813 - sqlalchemy.engine.Engine - INFO - DELETE FROM movies WHERE movies.id = $1::INTEGER
2024-09-25 17:24:13,813 - sqlalchemy.engine.Engine - INFO - [cached since 138s ago] (1,)
2024-09-25 17:24:13,813 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:24:13,828 - Movie-API - CRITICAL - Unhandled Exception: 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'id'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'director'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'release_year'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 327, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 176, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 4 validation errors:
  {'type': 'missing', 'loc': ('response', 'id'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'title'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'director'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}
  {'type': 'missing', 'loc': ('response', 'release_year'), 'msg': 'Field required', 'input': {'message': 'Movie deleted successfully'}}

2024-09-25 17:25:29,345 - Movie-API - INFO - Application startup...
2024-09-25 17:25:39,974 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 17:25:39,975 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 17:25:39,976 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 17:25:39,976 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 17:25:39,976 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 17:25:39,976 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 17:25:39,982 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:25:39,982 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies
2024-09-25 17:25:39,984 - sqlalchemy.engine.Engine - INFO - [generated in 0.00057s] ()
2024-09-25 17:25:39,988 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:25:55,546 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:25:55,546 - sqlalchemy.engine.Engine - INFO - INSERT INTO movies (id, title, director, release_year) VALUES ($1::INTEGER, $2::VARCHAR, $3::VARCHAR, $4::INTEGER)
2024-09-25 17:25:55,546 - sqlalchemy.engine.Engine - INFO - [generated in 0.00042s] (1, 'dada', 'dasda', 1989)
2024-09-25 17:25:55,551 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:25:55,555 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:25:55,555 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:25:55,555 - sqlalchemy.engine.Engine - INFO - [generated in 0.00041s] (1,)
2024-09-25 17:25:55,555 - Movie-API - INFO - Movie 'dada' created successfully.
2024-09-25 17:25:55,555 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:25:58,148 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:25:58,151 - sqlalchemy.engine.Engine - INFO - INSERT INTO movies (id, title, director, release_year) VALUES ($1::INTEGER, $2::VARCHAR, $3::VARCHAR, $4::INTEGER)
2024-09-25 17:25:58,152 - sqlalchemy.engine.Engine - INFO - [cached since 2.603s ago] (1, 'dada', 'dasda', 1989)
2024-09-25 17:25:58,153 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:25:58,155 - Movie-API - CRITICAL - Unhandled Exception: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "movies_pkey"
DETAIL:  Key (id)=(1) already exists.
[SQL: INSERT INTO movies (id, title, director, release_year) VALUES ($1::INTEGER, $2::VARCHAR, $3::VARCHAR, $4::INTEGER)]
[parameters: (1, 'dada', 'dasda', 1989)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 538, in _prepare_and_execute
    self._rows = deque(await prepared_stmt.fetch(*parameters))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\asyncpg\prepared_stmt.py", line 176, in fetch
    data = await self.__bind_execute(args, 0, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\asyncpg\prepared_stmt.py", line 241, in __bind_execute
    data, status, _ = await self.__do_execute(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\asyncpg\prepared_stmt.py", line 230, in __do_execute
    return await executor(protocol)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg\protocol\protocol.pyx", line 207, in bind_execute
asyncpg.exceptions.UniqueViolationError: duplicate key value violates unique constraint "movies_pkey"
DETAIL:  Key (id)=(1) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 572, in execute
    self._adapt_connection.await_(
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 550, in _prepare_and_execute
    self._handle_exception(error)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 501, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 784, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.IntegrityError: <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "movies_pkey"
DETAIL:  Key (id)=(1) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\git\MovieAPI\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\app\api\v1\movies.py", line 30, in create_movie
    response = await MovieService.create_movie(movie, db)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\app\services\movies_services.py", line 13, in create_movie
    await db.commit()  # Commit the transaction
    ^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 1009, in commit
    await greenlet_spawn(self.sync_session.commit)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4352, in flush
    self._flush(objects)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4487, in _flush
    with util.safe_reraise():
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 4448, in _flush
    flush_context.execute()
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1048, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 572, in execute
    self._adapt_connection.await_(
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 550, in _prepare_and_execute
    self._handle_exception(error)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 501, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "C:\git\MovieAPI\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 784, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.IntegrityError: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.UniqueViolationError'>: duplicate key value violates unique constraint "movies_pkey"
DETAIL:  Key (id)=(1) already exists.
[SQL: INSERT INTO movies (id, title, director, release_year) VALUES ($1::INTEGER, $2::VARCHAR, $3::VARCHAR, $4::INTEGER)]
[parameters: (1, 'dada', 'dasda', 1989)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2024-09-25 17:26:08,194 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:26:08,196 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:26:08,196 - sqlalchemy.engine.Engine - INFO - [generated in 0.00066s] (1,)
2024-09-25 17:26:08,196 - sqlalchemy.engine.Engine - INFO - DELETE FROM movies WHERE movies.id = $1::INTEGER
2024-09-25 17:26:08,196 - sqlalchemy.engine.Engine - INFO - [generated in 0.00048s] (1,)
2024-09-25 17:26:08,196 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:26:30,330 - Movie-API - INFO - Application shutdown...
2024-09-25 17:26:31,382 - Movie-API - INFO - Application startup...
2024-09-25 17:26:35,774 - Movie-API - INFO - Application shutdown...
2024-09-25 17:26:36,725 - Movie-API - INFO - Application startup...
2024-09-25 17:26:43,729 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 17:26:43,729 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 17:26:43,745 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 17:26:43,745 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 17:26:43,745 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 17:26:43,745 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 17:26:43,745 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:26:43,745 - sqlalchemy.engine.Engine - INFO - INSERT INTO movies (id, title, director, release_year) VALUES ($1::INTEGER, $2::VARCHAR, $3::VARCHAR, $4::INTEGER)
2024-09-25 17:26:43,754 - sqlalchemy.engine.Engine - INFO - [generated in 0.00053s] (1, 'dada', 'dasda', 1989)
2024-09-25 17:26:43,754 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:26:43,766 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:26:43,766 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:26:43,766 - sqlalchemy.engine.Engine - INFO - [generated in 0.00058s] (1,)
2024-09-25 17:26:43,766 - Movie-API - INFO - Movie 'dada' created successfully.
2024-09-25 17:26:43,766 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:26:48,200 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:26:48,200 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:26:48,200 - sqlalchemy.engine.Engine - INFO - [generated in 0.00057s] (1,)
2024-09-25 17:26:48,200 - sqlalchemy.engine.Engine - INFO - DELETE FROM movies WHERE movies.id = $1::INTEGER
2024-09-25 17:26:48,200 - sqlalchemy.engine.Engine - INFO - [generated in 0.00059s] (1,)
2024-09-25 17:26:48,207 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:27:36,682 - Movie-API - INFO - Application shutdown...
2024-09-25 17:27:37,551 - Movie-API - INFO - Application startup...
2024-09-25 17:27:49,418 - Movie-API - INFO - Application shutdown...
2024-09-25 17:27:50,302 - Movie-API - INFO - Application startup...
2024-09-25 17:28:00,435 - Movie-API - INFO - Application shutdown...
2024-09-25 17:28:01,416 - Movie-API - INFO - Application startup...
2024-09-25 17:28:07,006 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2024-09-25 17:28:07,006 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 17:28:07,021 - sqlalchemy.engine.Engine - INFO - select current_schema()
2024-09-25 17:28:07,021 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 17:28:07,021 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2024-09-25 17:28:07,021 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2024-09-25 17:28:07,021 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:28:07,021 - sqlalchemy.engine.Engine - INFO - INSERT INTO movies (id, title, director, release_year) VALUES ($1::INTEGER, $2::VARCHAR, $3::VARCHAR, $4::INTEGER)
2024-09-25 17:28:07,021 - sqlalchemy.engine.Engine - INFO - [generated in 0.00047s] (1, 'dada', 'dasda', 1989)
2024-09-25 17:28:07,021 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:28:07,041 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:28:07,042 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:28:07,042 - sqlalchemy.engine.Engine - INFO - [generated in 0.00053s] (1,)
2024-09-25 17:28:07,042 - Movie-API - INFO - Movie 'dada' created successfully.
2024-09-25 17:28:07,042 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:28:11,318 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:28:11,318 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:28:11,318 - sqlalchemy.engine.Engine - INFO - [generated in 0.00052s] (1,)
2024-09-25 17:28:11,318 - sqlalchemy.engine.Engine - INFO - DELETE FROM movies WHERE movies.id = $1::INTEGER
2024-09-25 17:28:11,318 - sqlalchemy.engine.Engine - INFO - [generated in 0.00041s] (1,)
2024-09-25 17:28:11,318 - sqlalchemy.engine.Engine - INFO - COMMIT
2024-09-25 17:28:14,790 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:28:14,790 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:28:14,790 - sqlalchemy.engine.Engine - INFO - [cached since 3.473s ago] (1,)
2024-09-25 17:28:14,793 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:28:17,878 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:28:17,879 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:28:17,880 - sqlalchemy.engine.Engine - INFO - [cached since 6.56s ago] (1,)
2024-09-25 17:28:17,881 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:28:27,353 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:28:27,353 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:28:27,353 - sqlalchemy.engine.Engine - INFO - [cached since 16.03s ago] (1,)
2024-09-25 17:28:27,355 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:28:28,880 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:28:28,881 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:28:28,881 - sqlalchemy.engine.Engine - INFO - [cached since 17.56s ago] (1,)
2024-09-25 17:28:28,886 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:28:33,859 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2024-09-25 17:28:33,860 - sqlalchemy.engine.Engine - INFO - SELECT movies.id, movies.title, movies.director, movies.release_year 
FROM movies 
WHERE movies.id = $1::INTEGER
2024-09-25 17:28:33,860 - sqlalchemy.engine.Engine - INFO - [cached since 22.54s ago] (12,)
2024-09-25 17:28:33,864 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2024-09-25 17:29:33,568 - Movie-API - INFO - Application shutdown...
